<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#World-Cup-Prediction" data-toc-modified-id="World-Cup-Prediction-1">World Cup Prediction</a></span></li><li><span><a href="#Merging-the-details-of-the-teams-participating-in-World-Cup" data-toc-modified-id="Merging-the-details-of-the-teams-participating-in-World-Cup-2">Merging the details of the teams participating in World Cup</a></span></li></ul></div>

## World Cup Prediction

In [1]:
# Importing all Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.ticker as plticker
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import warnings
warnings.filterwarnings('ignore')

Bad key "text.kerning_factor" on line 4 in
C:\Users\Vidya\Anaconda3\envs\learn-env\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
C:\Users\Vidya\Anaconda3\envs\learn-env\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

__Worldcup data contains data of all the world cup matches held from 1975.__  
__Results contain details of all the matches from 2010 - 2020.__

In [2]:
#Load data 
world_cup = pd.read_csv('data/World_Cup_Data.csv',parse_dates=True,encoding='latin1')
results = pd.read_csv('data/ODISummary2020.csv',parse_dates=True)

In [3]:
world_cup

,Team,Total,First,Last,Best,Total_Matches,Won,Lost,Tie,NR,Win%,Current Ranking
0,Australia,12,1975,2019,Champions 5 times,94,69,23,1,1,74.73,5
1,India,12,1975,2019,"Champions (1983, 2011)",84,53,29,1,1,64.45,2
2,West Indies,12,1975,2019,"Champions (1975, 1979)",80,43,35,0,2,55.12,9
3,England,12,1975,2019,Champions (2019),83,48,32,2,1,59.75,1
4,Pakistan,12,1975,2019,Champions (1992),79,45,32,0,2,58.44,6
5,Sri Lanka,12,1975,2019,Champions (1996),80,38,39,1,2,49.35,8
6,New Zealand,12,1975,2019,"Runners-up (2015, 2019)",89,54,33,1,1,61.93,3
7,South Africa,8,1992,2019,"Semi-finals (1992, 1999, 2007, 2015)",64,38,23,2,1,61.90,4
8,Zimbabwe,9,1983,2015,"Super 6s (1999, 2003)",57,11,42,1,3,21.29,14
9,Bangladesh,6,1999,2019,"Quarter-finals (2015), Super 8s (2007)",40,14,25,0,1,35.89,7
10,Ireland,3,2007,2015,Super 8s (2007),21,7,13,1,0,35.71,11
11,Netherlands,4,1996,2011,"Group Stage (1996, 2003, 2007, 2011)",20,2,18,0,0,10.00,12
12,Scotland,3,1999,2015,"Group Stage (1999, 2007, 2015)",14,0,14,0,0,0.00,15
13,Afghanistan,2,2015,2019,"Group Stage (2015, 2019)",15,1,14,0,0,6.66,10

In [4]:
results

,Match,Team1,Team2,Home/Away,Ground,Date,Month,Year,Country,Result,Margin,Winner
0,Bangladesh v England,Bangladesh,England,Away,Dhaka,2/28/2010,Feb,2010,England,Won,6 wickets,England
1,Bangladesh v England,Bangladesh,England,Away,Dhaka,3/2/2010,Mar,2010,England,Won,2 wickets,England
2,Bangladesh v England,Bangladesh,England,Away,Chattogram,3/5/2010,Mar,2010,England,Won,45 runs,England
3,Scotland v England,Scotland,England,Away,Edinburgh,6/19/2010,Jun,2010,England,Won,7 wickets,England
4,England v Australia,England,Australia,Home,Southampton,6/22/2010,Jun,2010,England,Won,4 wickets,England
...,...,...,...,...,...,...,...,...,...,...,...,...
2354,Afghanistan v Pakistan,Afghanistan,Pakistan,Home,Leeds,6/29/2019,Jun,2019,Afghanistan,Lost,3 wickets,Pakistan
2355,Afghanistan v West West Indies,Afghanistan,West Indies,Home,Leeds,7/4/2019,Jul,2019,Afghanistan,Lost,23 runs,West Indies
2356,Afghanistan v West West Indies,Afghanistan,West Indies,Home,Lucknow,11/6/2019,Nov,2019,Afghanistan,Lost,7 wickets,West Indies
2357,Afghanistan v West West Indies,Afghanistan,West Indies,Home,Lucknow,11/9/2019,Nov,2019,Afghanistan,Lost,47 runs,West Indies
2358,Afghanistan v West West Indies,Afghanistan,West Indies,Home,Lucknow,11/11/2019,Nov,2019,Afghanistan,Lost,5 wickets,West Indies

In [5]:
# Checking the matches won/lost by a specific country
df_india = results[(results['Team1'] == 'India') | (results['Team2'] == 'India')]
india = df_india.iloc[:]
india

,Match,Team1,Team2,Home/Away,Ground,Date,Month,Year,Country,Result,Margin,Winner
36,England v India,England,India,Home,Southampton,9/6/2011,Sep,2011,England,Won,7 wickets,England
37,England v India,England,India,Home,The Oval,9/9/2011,Sep,2011,England,Won,3 wickets,England
38,England v India,England,India,Home,Cardiff,9/16/2011,Sep,2011,England,Won,6 wickets,England
39,India v England,India,England,Away,Hyderabad (Deccan),10/14/2011,Oct,2011,England,Lost,126 runs,India
40,India v England,India,England,Away,Delhi,10/17/2011,Oct,2011,England,Lost,8 wickets,India
...,...,...,...,...,...,...,...,...,...,...,...,...
2016,Bangladesh v India,Bangladesh,India,Home,Birmingham,7/2/2019,Jul,2019,Bangladesh,Lost,28 runs,India
2080,India v Ireland,India,Ireland,Away,Bengaluru,3/6/2011,Mar,2011,Ireland,Lost,5 wickets,India
2110,India v Ireland,India,Ireland,Away,Hamilton,3/10/2015,Mar,2015,Ireland,Lost,8 wickets,India
2267,Afghanistan v India,Afghanistan,India,Home,Dhaka,3/5/2014,Mar,2014,Afghanistan,Lost,8 wickets,India
2352,Afghanistan v India,Afghanistan,India,Home,Southampton,6/22/2019,Jun,2019,Afghanistan,Lost,11 runs,India

In [6]:
#creating a column for matches played by a country in 2010
india_2010 = india[india.Year == 2010]
india_2010

,Match,Team1,Team2,Home/Away,Ground,Date,Month,Year,Country,Result,Margin,Winner
227,India v Australia,India,Australia,Away,Visakhapatnam,10/20/2010,Oct,2010,Australia,Lost,5 wickets,India
418,India v South Africa,India,Africa,Away,Jaipur,2/21/2010,Feb,2010,South Africa,Lost,1 runs,India
419,India v South Africa,India,Africa,Away,Gwalior,2/24/2010,Feb,2010,South Africa,Lost,153 runs,India
420,India v South Africa,India,Africa,Away,Ahmedabad,2/27/2010,Feb,2010,South Africa,Won,90 runs,South Africa
802,India v New Zealand,India,Zealand,Away,Dambulla,8/10/2010,Aug,2010,New Zealand,Won,200 runs,New Zealand
804,India v New Zealand,India,Zealand,Away,Dambulla,8/25/2010,Aug,2010,New Zealand,Lost,105 runs,India
809,India v New Zealand,India,Zealand,Away,Guwahati,11/28/2010,Nov,2010,New Zealand,Lost,40 runs,India
810,India v New Zealand,India,Zealand,Away,Jaipur,12/1/2010,Dec,2010,New Zealand,Lost,8 wickets,India
811,India v New Zealand,India,Zealand,Away,Vadodara,12/4/2010,Dec,2010,New Zealand,Lost,9 wickets,India
812,India v New Zealand,India,Zealand,Away,Bengaluru,12/7/2010,Dec,2010,New Zealand,Lost,5 wickets,India
813,India v New Zealand,India,Zealand,Away,Chennai,12/10/2010,Dec,2010,New Zealand,Lost,8 wickets,India
978,India v Sri Lanka,India,Sri Lanka,Home,Dhaka,1/5/2010,Jan,2010,India,Lost,5 wickets,Sri Lanka
979,Bangladesh v India,Bangladesh,India,Away,Dhaka,1/7/2010,Jan,2010,India,Won,6 wickets,India
980,India v Sri Lanka,India,Sri Lanka,Home,Dhaka,1/10/2010,Jan,2010,India,Won,8 wickets,India
981,Bangladesh v India,Bangladesh,India,Away,Dhaka,1/11/2010,Jan,2010,India,Won,6 wickets,India
982,India v Sri Lanka,India,Sri Lanka,Home,Dhaka,1/13/2010,Jan,2010,India,Lost,4 wickets,Sri Lanka
983,India v South Africa,India,Africa,Home,Jaipur,2/21/2010,Feb,2010,India,Won,1 runs,India
984,India v South Africa,India,Africa,Home,Gwalior,2/24/2010,Feb,2010,India,Won,153 runs,India
985,India v South Africa,India,Africa,Home,Ahmedabad,2/27/2010,Feb,2010,India,Lost,90 runs,Africa
986,Zimbabwe v India,Zimbabwe,India,Away,Bulawayo,5/28/2010,May,2010,India,Lost,6 wickets,Zimbabwe
987,India v Sri Lanka,India,Sri Lanka,Home,Bulawayo,5/30/2010,May,2010,India,Won,7 wickets,India
988,Zimbabwe v India,Zimbabwe,India,Away,Harare,6/3/2010,Jun,2010,India,Lost,7 wickets,Zimbabwe
989,India v Sri Lanka,India,Sri Lanka,Home,Harare,6/5/2010,Jun,2010,India,Lost,6 wickets,Sri Lanka
990,Bangladesh v India,Bangladesh,India,Away,Dambulla,6/16/2010,Jun,2010,India,Won,6 wickets,India
991,India v Pakistan,India,Pakistan,Home,Dambulla,6/19/2010,Jun,2010,India,Won,3 wickets,India
992,Sri Lanka v India,Sri,India,Away,Dambulla,6/22/2010,Jun,2010,India,Lost,7 wickets,Sri
993,Sri Lanka v India,Sri,India,Away,Dambulla,6/24/2010,Jun,2010,India,Won,81 runs,India
994,India v New Zealand,India,Zealand,Home,Dambulla,8/10/2010,Aug,2010,India,Lost,200 runs,Zealand
995,Sri Lanka v India,Sri,India,Away,Dambulla,8/16/2010,Aug,2010,India,Won,6 wickets,India
996,Sri Lanka v India,Sri,India,Away,Dambulla,8/22/2010,Aug,2010,India,Lost,8 wickets,Sri
997,India v New Zealand,India,Zealand,Home,Dambulla,8/25/2010,Aug,2010,India,Won,105 runs,India
998,Sri Lanka v India,Sri,India,Away,Dambulla,8/28/2010,Aug,2010,India,Lost,74 runs,Sri
999,India v Australia,India,Australia,Home,Visakhapatnam,10/20/2010,Oct,2010,India,Won,5 wickets,India
1000,India v New Zealand,India,Zealand,Home,Guwahati,11/28/2010,Nov,2010,India,Won,40 runs,India
1001,India v New Zealand,India,Zealand,Home,Jaipur,12/1/2010,Dec,2010,India,Won,8 wickets,India
1002,India v New Zealand,India,Zealand,Home,Vadodara,12/4/2010,Dec,2010,India,Won,9 wickets,India
1003,India v New Zealand,India,Zealand,Home,Bengaluru,12/7/2010,Dec,2010,India,Won,5 wickets,India
1004,India v New Zealand,India,Zealand,Home,Chennai,12/10/2010,Dec,2010,India,Won,8 wickets,India
1226,India v Pakistan,India,Pakistan,Away,Dambulla,6/19/2010,Jun,2010,Pakistan,Lost,3 wickets,India
1431,India v Sri Lanka,India,Sri Lanka,Away,Dhaka,1/5/2010,Jan,2010,Sri Lanka,Won,5 wickets,Sri Lanka
1433,India v Sri Lanka,India,Sri Lanka,Away,Dhaka,1/10/2010,Jan,2010,Sri Lanka,Lost,8 wickets,India
1434,India v Sri Lanka,India,Sri Lanka,Away,Dhaka,1/13/2010,Jan,2010,Sri Lanka,Won,4 wickets,Sri Lanka
1435,India v Sri Lanka,India,Sri Lanka,Away,Bulawayo,5/30/2010,May,2010,Sri Lanka,Lost,7 wickets,India
1437,India v Sri Lanka,India,Sri Lanka,Away,Harare,6/5/2010,Jun,2010,Sri Lanka,Won,6 wickets,Sri Lanka
1442,Sri Lanka v India,Sri,India,Home,Dambulla,6/22/2010,Jun,2010,Sri Lanka,Won,7 wickets,Sri Lanka
1443,Sri Lanka v India,Sri,India,Home,Dambulla,6/24/2010,Jun,2010,Sri Lanka,Lost,81 runs,India
1445,Sri Lanka v India,Sri,India,Home,Dambulla,8/16/2010,Aug,2010,Sri Lanka,Lost,6 wickets,India
1446,Sri Lanka v India,Sri,India,Home,Dambulla,8/22/2010,Aug,2010,Sri Lanka,Won,8 wickets,Sri Lanka
1447,Sri Lanka v India,Sri,India,Home,Dambulla,8/28/2010,Aug,2010,Sri Lanka,Won,74 runs,Sri Lanka
1678,Zimbabwe v India,Zimbabwe,India,Home,Bulawayo,5/28/2010,May,2010,Zimbabwe,Won,6 wickets,Zimbabwe
1680,Zimbabwe v India,Zimbabwe,India,Home,Harare,6/3/2010,Jun,2010,Zimbabwe,Won,7 wickets,Zimbabwe
1865,Bangladesh v India,Bangladesh,India,Home,Dhaka,1/7/2010,Jan,2010,Bangladesh,Lost,6 wickets,India
1867,Bangladesh v India,Bangladesh,India,Home,Dhaka,1/11/2010,Jan,2010,Bangladesh,Lost,6 wickets,India
1874,Bangladesh v India,Bangladesh,India,Home,Dambulla,6/16/2010,Jun,2010,Bangladesh,Lost,6 wickets,India

## Merging the details of the teams participating in World Cup

In [7]:
worldcup_teams = ['England', ' South Africa', '', 'West Indies', 
            'Pakistan', 'New Zealand', 'Sri Lanka', 'Afghanistan', 
            'Australia', 'Bangladesh', 'India']
df_teams_1 = results[results['Team1'].isin(worldcup_teams)]
df_teams_2 = results[results['Team2'].isin(worldcup_teams)]
df_teams = pd.concat((df_teams_1, df_teams_2))
df_teams.drop_duplicates()
df_teams.count()

,Match,Team1,Team2,Home/Away,Ground,Date,Month,Year,Country,Result,Margin,Winner
0,Bangladesh v England,Bangladesh,England,Away,Dhaka,2/28/2010,Feb,2010,England,Won,6 wickets,England
1,Bangladesh v England,Bangladesh,England,Away,Dhaka,3/2/2010,Mar,2010,England,Won,2 wickets,England
2,Bangladesh v England,Bangladesh,England,Away,Chattogram,3/5/2010,Mar,2010,England,Won,45 runs,England
4,England v Australia,England,Australia,Home,Southampton,6/22/2010,Jun,2010,England,Won,4 wickets,England
5,England v Australia,England,Australia,Home,Cardiff,6/24/2010,Jun,2010,England,Won,4 wickets,England
...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Ireland v Afghanistan,Ireland,Afghanistan,Away,Belfast,8/29/2018,Aug,2018,Afghanistan,Lost,3 wickets,Ireland
2335,Ireland v Afghanistan,Ireland,Afghanistan,Away,Belfast,8/31/2018,Aug,2018,Afghanistan,Won,8 wickets,Afghanistan
2344,Scotland v Afghanistan,Scotland,Afghanistan,Away,Edinburgh,5/10/2019,May,2019,Afghanistan,Won,2 runs,Afghanistan
2345,Ireland v Afghanistan,Ireland,Afghanistan,Away,Belfast,5/19/2019,May,2019,Afghanistan,Lost,72 runs,Ireland
2346,Ireland v Afghanistan,Ireland,Afghanistan,Away,Belfast,5/21/2019,May,2019,Afghanistan,Won,126 runs,Afghanistan

Match        2778
Team1        2778
Team2        2778
Home/Away    2778
Ground       2778
Date         2778
Month        2778
Year         2778
Country      2778
Result       2778
Margin       2778
Winner       2778
dtype: int64

In [8]:
df_teams.head()

,Match,Team1,Team2,Home/Away,Ground,Date,Month,Year,Country,Result,Margin,Winner
0,Bangladesh v England,Bangladesh,England,Away,Dhaka,2/28/2010,Feb,2010,England,Won,6 wickets,England
1,Bangladesh v England,Bangladesh,England,Away,Dhaka,3/2/2010,Mar,2010,England,Won,2 wickets,England
2,Bangladesh v England,Bangladesh,England,Away,Chattogram,3/5/2010,Mar,2010,England,Won,45 runs,England
4,England v Australia,England,Australia,Home,Southampton,6/22/2010,Jun,2010,England,Won,4 wickets,England
5,England v Australia,England,Australia,Home,Cardiff,6/24/2010,Jun,2010,England,Won,4 wickets,England

__We want only the Teams name and the winners of the matches so that this can used to train our data.__

In [9]:
df_teams_2010 = df_teams.filter(['Team1','Team2', 'Winner'],axis=1)
df_teams_2010.head()

        Team1      Team2   Winner
0  Bangladesh    England  England
1  Bangladesh    England  England
2  Bangladesh    England  England
4     England  Australia  England
5     England  Australia  England

In [10]:
df_teams_2010 = df_teams_2010.reset_index(drop=True)
df_teams_2010.loc[df_teams_2010.Winner == df_teams_2010.Team1,'winning_team']=1
df_teams_2010.loc[df_teams_2010.Winner == df_teams_2010.Team2, 'winning_team']=2

In [11]:
df_teams_2010

            Team1        Team2       Winner  winning_team
0      Bangladesh      England      England           2.0
1      Bangladesh      England      England           2.0
2      Bangladesh      England      England           2.0
3         England    Australia      England           1.0
4         England    Australia      England           1.0
...           ...          ...          ...           ...
2773  Afghanistan     Pakistan     Pakistan           2.0
2774  Afghanistan  West Indies  West Indies           2.0
2775  Afghanistan  West Indies  West Indies           2.0
2776  Afghanistan  West Indies  West Indies           2.0
2777  Afghanistan  West Indies  West Indies           2.0

[2778 rows x 4 columns]

In [12]:
df_teams_2010 = df_teams_2010.drop(['winning_team'], axis=1)

df_teams_2010.head()

        Team1      Team2   Winner
0  Bangladesh    England  England
1  Bangladesh    England  England
2  Bangladesh    England  England
3     England  Australia  England
4     England  Australia  England

In [13]:
# convert Team-1 and Team-2 from categorical variables into continous variables

final = pd.get_dummies(df_teams_2010, prefix=['Team1', 'Team2'], columns=['Team1', 'Team2'])

X = final.drop(['Winner'], axis=1)
y = final["Winner"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [14]:
final.head()

,Winner,Team1_Afghanistan,Team1_Australia,Team1_Bangladesh,Team1_Canada,Team1_England,Team1_Hong,Team1_India,Team1_Ireland,Team1_Kenya,...,Team2_Ireland,Team2_Kenya,Team2_Netherlands,Team2_Pakistan,Team2_Scotland,Team2_Sri Lanka,Team2_UAE,Team2_West Indies,Team2_Zealand,Team2_Zimbabwe
0,England,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,England,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,England,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,England,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,England,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
#Using Random Forest to train and test our data
rf = RandomForestClassifier(n_estimators=100, max_depth=20,
                              random_state=0)
rf.fit(X_train, y_train) 


score = rf.score(X_train, y_train)
score2 = rf.score(X_test, y_test)


print("Training set accuracy: ", '%.3f'%(score))
print("Test set accuracy: ", '%.3f'%(score2))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=20, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

Training set accuracy:  0.679
Test set accuracy:  0.644

__Ranking dataset contains the current rankings of the teams.__  
__Fxitures are the matches that will be held during World Cup.__

In [16]:
ranking = pd.read_csv('data/icc_rankings.csv') 
fixtures = pd.read_csv('data/matches.csv')
pred_set = []

In [17]:
# Inerting the columns of rankings of the teams.
fixtures.insert(1, 'Team1_position', fixtures['Team1'].map(ranking.set_index('Team')['Current_Ranking']))
fixtures.insert(2, 'Team2_position', fixtures['Team2'].map(ranking.set_index('Team')['Current_Ranking']))

fixtures = fixtures.iloc[:45, :]
fixtures.tail()

,Team1,Team1_position,Team2_position,Team2,Result,Unnamed: 3,Unnamed: 4,Unnamed: 5
40,England,1.0,3.0,New Zealand,NaN,NaN,NaN,NaN
41,Afghanistan,10.0,9.0,West Indies,NaN,NaN,NaN,NaN
42,Pakistan,6.0,7.0,Bangladesh,NaN,NaN,NaN,NaN
43,Sri Lanka,8.0,2.0,India,NaN,NaN,NaN,NaN
44,Australia,5.0,4.0,South Africa,NaN,NaN,NaN,NaN

In [18]:
fixtures.drop(['Unnamed: 3','Unnamed: 4','Unnamed: 5'],axis=1)

           Team1  Team1_position  Team2_position         Team2  Result
0        England             1.0             4.0  South Africa     NaN
1    West Indies             9.0             6.0      Pakistan     NaN
2    New Zealand             3.0             8.0     Sri Lanka     NaN
3    Afghanistan            10.0             5.0     Australia     NaN
4   South Africa             4.0             7.0    Bangladesh     NaN
5        England             1.0             6.0      Pakistan     NaN
6    Afghanistan            10.0             8.0     Sri Lanka     NaN
7   South Africa             4.0             2.0         India     NaN
8     Bangladesh             7.0             3.0   New Zealand     NaN
9      Australia             5.0             9.0   West Indies     NaN
10      Pakistan             6.0             8.0     Sri Lanka     NaN
11       England             1.0             7.0    Bangladesh     NaN
12   Afghanistan            10.0             3.0   New Zealand     NaN
13         India             2.0             5.0     Australia     NaN
14  South Africa             4.0             9.0   West Indies     NaN
15    Bangladesh             7.0             8.0     Sri Lanka     NaN
16     Australia             5.0             6.0      Pakistan     NaN
17         India             2.0             3.0   New Zealand     NaN
18       England             1.0             9.0   West Indies     NaN
19     Sri Lanka             8.0             5.0     Australia     NaN
20  South Africa             4.0            10.0   Afghanistan     NaN
21         India             2.0             6.0      Pakistan     NaN
22   West Indies             9.0             7.0    Bangladesh     NaN
23       England             1.0            10.0   Afghanistan     NaN
24   New Zealand             3.0             4.0  South Africa     NaN
25     Australia             5.0             7.0    Bangladesh     NaN
26       England             1.0             8.0     Sri Lanka     NaN
27         India             2.0            10.0   Afghanistan     NaN
28   West Indies             9.0             3.0   New Zealand     NaN
29      Pakistan             6.0             4.0  South Africa     NaN
30    Bangladesh             7.0            10.0   Afghanistan     NaN
31       England             1.0             5.0     Australia     NaN
32   New Zealand             3.0             6.0      Pakistan     NaN
33   West Indies             9.0             2.0         India     NaN
34     Sri Lanka             8.0             4.0  South Africa     NaN
35      Pakistan             6.0            10.0   Afghanistan     NaN
36   New Zealand             3.0             5.0     Australia     NaN
37       England             1.0             2.0         India     NaN
38     Sri Lanka             8.0             9.0   West Indies     NaN
39    Bangladesh             7.0             2.0         India     NaN
40       England             1.0             3.0   New Zealand     NaN
41   Afghanistan            10.0             9.0   West Indies     NaN
42      Pakistan             6.0             7.0    Bangladesh     NaN
43     Sri Lanka             8.0             2.0         India     NaN
44     Australia             5.0             4.0  South Africa     NaN

In [19]:
# Loop to add teams to new prediction dataset based on the ranking position of each team
for index, row in fixtures.iterrows():
    if row['Team1_position'] < row['Team2_position']:
        pred_set.append({'Team1': row['Team1'], 'Team2': row['Team2'], 'winning_team': None})
    else:
        pred_set.append({'Team1': row['Team2'], 'Team2': row['Team1'], 'winning_team': None})
        
pred_set = pd.DataFrame(pred_set)
backup_pred_set = pred_set
pred_set.head()

          Team1         Team2 winning_team
0       England  South Africa         None
1      Pakistan   West Indies         None
2   New Zealand     Sri Lanka         None
3     Australia   Afghanistan         None
4  South Africa    Bangladesh         None

In [20]:
# Get dummy variables and drop winning_team column

pred_set = pd.get_dummies(pred_set, prefix=['Team1', 'Team2'], columns=['Team1', 'Team2'])

# Add missing columns compared to the model's training dataset
missing_cols = set(final.columns) - set(pred_set.columns)
for c in missing_cols:
    pred_set[c] = 0
pred_set = pred_set[final.columns]


pred_set = pred_set.drop(['Winner'], axis=1)
pred_set.head()

,Team1_Afghanistan,Team1_Australia,Team1_Bangladesh,Team1_Canada,Team1_England,Team1_Hong,Team1_India,Team1_Ireland,Team1_Kenya,Team1_Netherlands,...,Team2_Ireland,Team2_Kenya,Team2_Netherlands,Team2_Pakistan,Team2_Scotland,Team2_Sri Lanka,Team2_UAE,Team2_West Indies,Team2_Zealand,Team2_Zimbabwe
0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
#Group Matches Predictions 
predictions = rf.predict(pred_set)
for i in range(fixtures.shape[0]):
    print(backup_pred_set.iloc[i, 1] + " and " + backup_pred_set.iloc[i, 0])
    winner=""
    if predictions[i] == 1:
        winner=backup_pred_set.iloc[i, 1]        
        backup_pred_set.iloc[i, 2] = winner
    else:
        winner=backup_pred_set.iloc[i, 0]        
        backup_pred_set.iloc[i, 2] = winner    
    print("Winner: " + winner+"\n")

South Africa and England
Winner: England

West Indies and Pakistan
Winner: Pakistan

Sri Lanka and New Zealand
Winner: New Zealand

Afghanistan and Australia
Winner: Australia

Bangladesh and South Africa
Winner: South Africa

Pakistan and England
Winner: England

Afghanistan and Sri Lanka
Winner: Sri Lanka

South Africa and India
Winner: India

Bangladesh and New Zealand
Winner: New Zealand

West Indies and Australia
Winner: Australia

Sri Lanka and Pakistan
Winner: Pakistan

Bangladesh and England
Winner: England

Afghanistan and New Zealand
Winner: New Zealand

Australia and India
Winner: India

West Indies and South Africa
Winner: South Africa

Sri Lanka and Bangladesh
Winner: Bangladesh

Pakistan and Australia
Winner: Australia

New Zealand and India
Winner: India

West Indies and England
Winner: England

Sri Lanka and Australia
Winner: Australia

Afghanistan and South Africa
Winner: South Africa

Pakistan and India
Winner: India

West Indies and Bangladesh
Winner: Bangladesh

Afghanistan and England
Winner: England

South Africa and New Zealand
Winner: New Zealand

Bangladesh and Australia
Winner: Australia

Sri Lanka and England
Winner: England

Afghanistan and India
Winner: India

West Indies and New Zealand
Winner: New Zealand

Pakistan and South Africa
Winner: South Africa

Afghanistan and Bangladesh
Winner: Bangladesh

Australia and England
Winner: England

Pakistan and New Zealand
Winner: New Zealand

West Indies and India
Winner: India

Sri Lanka and South Africa
Winner: South Africa

Afghanistan and Pakistan
Winner: Pakistan

Australia and New Zealand
Winner: New Zealand

India and England
Winner: England

West Indies and Sri Lanka
Winner: Sri Lanka

Bangladesh and India
Winner: India

New Zealand and England
Winner: England

Afghanistan and West Indies
Winner: West Indies

Bangladesh and Pakistan
Winner: Pakistan

Sri Lanka and India
Winner: India

Australia and South Africa
Winner: South Africa

In [22]:
backup_pred_set

           Team1         Team2  winning_team
0        England  South Africa       England
1       Pakistan   West Indies      Pakistan
2    New Zealand     Sri Lanka   New Zealand
3      Australia   Afghanistan     Australia
4   South Africa    Bangladesh  South Africa
5        England      Pakistan       England
6      Sri Lanka   Afghanistan     Sri Lanka
7          India  South Africa         India
8    New Zealand    Bangladesh   New Zealand
9      Australia   West Indies     Australia
10      Pakistan     Sri Lanka      Pakistan
11       England    Bangladesh       England
12   New Zealand   Afghanistan   New Zealand
13         India     Australia         India
14  South Africa   West Indies  South Africa
15    Bangladesh     Sri Lanka    Bangladesh
16     Australia      Pakistan     Australia
17         India   New Zealand         India
18       England   West Indies       England
19     Australia     Sri Lanka     Australia
20  South Africa   Afghanistan  South Africa
21         India      Pakistan         India
22    Bangladesh   West Indies    Bangladesh
23       England   Afghanistan       England
24   New Zealand  South Africa   New Zealand
25     Australia    Bangladesh     Australia
26       England     Sri Lanka       England
27         India   Afghanistan         India
28   New Zealand   West Indies   New Zealand
29  South Africa      Pakistan  South Africa
30    Bangladesh   Afghanistan    Bangladesh
31       England     Australia       England
32   New Zealand      Pakistan   New Zealand
33         India   West Indies         India
34  South Africa     Sri Lanka  South Africa
35      Pakistan   Afghanistan      Pakistan
36   New Zealand     Australia   New Zealand
37       England         India       England
38     Sri Lanka   West Indies     Sri Lanka
39         India    Bangladesh         India
40       England   New Zealand       England
41   West Indies   Afghanistan   West Indies
42      Pakistan    Bangladesh      Pakistan
43         India     Sri Lanka         India
44  South Africa     Australia  South Africa

In [23]:
top_res = backup_pred_set['winning_team'].value_counts()

In [24]:
top_res.head(4)

England         9
India           8
New Zealand     7
South Africa    6
Name: winning_team, dtype: int64

In [25]:
# List of tuples before 
semi = top_res.head(4)

In [26]:
semi.index[0]

'England'

In [27]:
semi_fin=[(semi.index[0],semi.index[3]),(semi.index[1],semi.index[2])]

In [28]:
semi_fin

[('England', 'South Africa'), ('India', 'New Zealand')]

In [33]:
def final_predict(matches, ranking, final, logreg):

    # Initialization of auxiliary list for data cleaning
    positions = []

    # Loop to retrieve each team's position according to ICC ranking
    for match in matches:
        positions.append(ranking.loc[ranking['Team'] == match[0],'Current_Ranking'].iloc[0])
        positions.append(ranking.loc[ranking['Team'] == match[1],'Current_Ranking'].iloc[0])
    
    # Creating the DataFrame for prediction
    pred_set = []

    # Initializing iterators for while loop
    i = 0
    j = 0

    # 'i' will be the iterator for the 'positions' list, and 'j' for the list of matches (list of tuples)
    while i < len(positions):
        dict1 = {}

        # If position of first team is better then this team will be the 'Team_1' team, and vice-versa
        if positions[i] < positions[i + 1]:
            dict1.update({'Team1': matches[j][0], 'Team2': matches[j][1]})
        else:
            dict1.update({'Team1': matches[j][1], 'Team2': matches[j][0]})

        # Append updated dictionary to the list, that will later be converted into a DataFrame
        pred_set.append(dict1)
        i += 2
        j += 1
        
    # Convert into DataFrame
    pred_set = pd.DataFrame(pred_set)
    backup_pred_set = pred_set

    # Get dummy variables and drop winning_team column
    pred_set = pd.get_dummies(pred_set, prefix=['Team1', 'Team2'], columns=['Team1', 'Team2'])

    # Add missing columns compared to the model's training dataset
    missing_cols2 = set(final.columns) - set(pred_set.columns)
    for c in missing_cols2:
        pred_set[c] = 0
    pred_set = pred_set[final.columns]

    pred_set = pred_set.drop(['Winner'], axis=1)

    # Prediction
    predictions = logreg.predict(pred_set)
    winner = []
    for i in range(len(pred_set)):
        print(backup_pred_set.iloc[i, 1] + " and " + backup_pred_set.iloc[i, 0])
        if predictions[i] == 1:
            print("Winner: " + backup_pred_set.iloc[i, 1])
            winner.append(backup_pred_set.iloc[i, 1])
        else:
            print("Winner: " + backup_pred_set.iloc[i, 0])
            winner.append(backup_pred_set.iloc[i, 0])
        print("")
    return winner

In [34]:
finals = final_predict(semi_fin, ranking, final, rf)
finals

South Africa and England
Winner: England

New Zealand and India
Winner: India

['England', 'India']

In [35]:
# Make it a tuple
final_teams = [(finals[0],finals[1])]
final_teams

[('England', 'India')]

In [36]:
final_predict(final_teams, ranking, final, rf)

India and England
Winner: England

['England']