<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
# World Cup Data

In [8]:
# Importing all Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
import matplotlib.ticker as plticker
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

import warnings
warnings.filterwarnings('ignore')

In [15]:
#Load data 
world_cup = pd.read_csv('data/World_Cup_Data.csv',parse_dates=True,encoding='latin1')
results = pd.read_csv('data/ODISummary2020.csv',parse_dates=True)

In [16]:
world_cup

,Team,Total,First,Last,Best,Total_Matches,Won,Lost,Tie,NR,Win%,Current Ranking
0,Australia,12,1975,2019,Champions 5 times,94,69,23,1,1,74.73,5
1,India,12,1975,2019,"Champions (1983, 2011)",84,53,29,1,1,64.45,2
2,West Indies,12,1975,2019,"Champions (1975, 1979)",80,43,35,0,2,55.12,9
3,England,12,1975,2019,Champions (2019),83,48,32,2,1,59.75,1
4,Pakistan,12,1975,2019,Champions (1992),79,45,32,0,2,58.44,6
5,Sri Lanka,12,1975,2019,Champions (1996),80,38,39,1,2,49.35,8
6,New Zealand,12,1975,2019,"Runners-up (2015, 2019)",89,54,33,1,1,61.93,3
7,South Africa,8,1992,2019,"Semi-finals (1992, 1999, 2007, 2015)",64,38,23,2,1,61.90,4
8,Zimbabwe,9,1983,2015,"Super 6s (1999, 2003)",57,11,42,1,3,21.29,14
9,Bangladesh,6,1999,2019,"Quarter-finals (2015), Super 8s (2007)",40,14,25,0,1,35.89,7
10,Ireland,3,2007,2015,Super 8s (2007),21,7,13,1,0,35.71,11
11,Netherlands,4,1996,2011,"Group Stage (1996, 2003, 2007, 2011)",20,2,18,0,0,10.00,12
12,Scotland,3,1999,2015,"Group Stage (1999, 2007, 2015)",14,0,14,0,0,0.00,15
13,Afghanistan,2,2015,2019,"Group Stage (2015, 2019)",15,1,14,0,0,6.66,10

In [17]:
results

,Match,Team1,Team2,Home/Away,Ground,Date,Month,Year,Country,Result,Margin,Winner
0,Bangladesh v England,Bangladesh,England,Away,Dhaka,2/28/2010,Feb,2010,England,Won,6 wickets,England
1,Bangladesh v England,Bangladesh,England,Away,Dhaka,3/2/2010,Mar,2010,England,Won,2 wickets,England
2,Bangladesh v England,Bangladesh,England,Away,Chattogram,3/5/2010,Mar,2010,England,Won,45 runs,England
3,Scotland v England,Scotland,England,Away,Edinburgh,6/19/2010,Jun,2010,England,Won,7 wickets,England
4,England v Australia,England,Australia,Home,Southampton,6/22/2010,Jun,2010,England,Won,4 wickets,England
...,...,...,...,...,...,...,...,...,...,...,...,...
2354,Afghanistan v Pakistan,Afghanistan,Pakistan,Home,Leeds,6/29/2019,Jun,2019,Afghanistan,Lost,3 wickets,Pakistan
2355,Afghanistan v West West Indies,Afghanistan,West Indies,Home,Leeds,7/4/2019,Jul,2019,Afghanistan,Lost,23 runs,West Indies
2356,Afghanistan v West West Indies,Afghanistan,West Indies,Home,Lucknow,11/6/2019,Nov,2019,Afghanistan,Lost,7 wickets,West Indies
2357,Afghanistan v West West Indies,Afghanistan,West Indies,Home,Lucknow,11/9/2019,Nov,2019,Afghanistan,Lost,47 runs,West Indies
2358,Afghanistan v West West Indies,Afghanistan,West Indies,Home,Lucknow,11/11/2019,Nov,2019,Afghanistan,Lost,5 wickets,West Indies

In [21]:
df = results[(results['Team1'] == 'India') | (results['Team2'] == 'India')]
india = df.iloc[:]
india

,Match,Team1,Team2,Home/Away,Ground,Date,Month,Year,Country,Result,Margin,Winner
36,England v India,England,India,Home,Southampton,9/6/2011,Sep,2011,England,Won,7 wickets,England
37,England v India,England,India,Home,The Oval,9/9/2011,Sep,2011,England,Won,3 wickets,England
38,England v India,England,India,Home,Cardiff,9/16/2011,Sep,2011,England,Won,6 wickets,England
39,India v England,India,England,Away,Hyderabad (Deccan),10/14/2011,Oct,2011,England,Lost,126 runs,India
40,India v England,India,England,Away,Delhi,10/17/2011,Oct,2011,England,Lost,8 wickets,India
...,...,...,...,...,...,...,...,...,...,...,...,...
2016,Bangladesh v India,Bangladesh,India,Home,Birmingham,7/2/2019,Jul,2019,Bangladesh,Lost,28 runs,India
2080,India v Ireland,India,Ireland,Away,Bengaluru,3/6/2011,Mar,2011,Ireland,Lost,5 wickets,India
2110,India v Ireland,India,Ireland,Away,Hamilton,3/10/2015,Mar,2015,Ireland,Lost,8 wickets,India
2267,Afghanistan v India,Afghanistan,India,Home,Dhaka,3/5/2014,Mar,2014,Afghanistan,Lost,8 wickets,India
2352,Afghanistan v India,Afghanistan,India,Home,Southampton,6/22/2019,Jun,2019,Afghanistan,Lost,11 runs,India

In [28]:
#creating a column for matches played in 2010
# year = []
# for row in india['Year']:
#     year.append(int(row[7:]))
# india ['Match_year']= year
india_2010 = india[india.Year == 2010]
india_2010.count()

Match         54
Team1         54
Team2         54
Home/Away     54
Ground        54
Date          54
Month         54
Year          54
Country       54
Result        54
Margin        54
Winner        54
Match_year    54
dtype: int64